# Generated by Django 2.1.7 on 2019-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_s', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('page', models.CharField(max_length=20, null=True)),
                ('position', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('pages', models.CharField(max_length=20)),
                ('publication_date', models.CharField(max_length=50)),
                ('sales_rank', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Enter a book keyword (e.g. drug history)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=100)),
            ],
            options={
                'ordering': ['-my_field_name'],
            },
        ),
    ]
